name: Atata
short_description: "C#/.NET Test Automation Framework"
description: "C#/.NET automated web testing full featured framework"
url: https://atata-framework.github.io
baseurl: ""
timezone: "Europe/Kiev"

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: false

gems:
  - jekyll-sitemap

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post

# Permalinks
#permalink: pretty
permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!--more-->

author:
  name: Yevgeniy Shunevych
  github: YevgeniyShunevych
  url: https://github.com/YevgeniyShunevych
  email: yevgeniy.shunevych@gmail.com

nav_links:
  Getting Started: "getting-started"
  Components: "components"
  Control Search: "control-search"
  Triggers: "triggers"
  Tutorials: "tutorials"
  Examples: "examples"
  Blog: "blog"
  Contact: "contact"

getting-started:
  - name: Introduction
  - name: Installation
    items:
      - Via Atata Templates
      - Via NuGet
  - name: Usage
    items:
      - Create Project
      - Define Settings
      - Define Page Object Class
      - Implement Test
      - View Log
  - name: Demo
  - name: Set Up
    items:
      - Driver
      - Logging
      - Screenshots
      - Other
  - name: Navigation
    items:
      - Go
      - Transition

components:
  - name: Base Components
    items:
      - UIComponent
      - Control
      - PageObject
      - Page
      - PopupWindow
      - Field
      - EditableField
  - name: Inputs
    items:
      - Input
      - TextInput
      - PasswordInput
      - NumberInput
      - DateInput
      - TimeInput
      - FileInput
      - HiddenInput
      - CheckBox
      - CheckBoxList
      - RadioButton
      - RadioButtonList
      - SearchInput
  - name: Select
    items:
      - Option
  - name: TextArea
  - name: Button
  - name: Link
  - name: Clickable
  - name: Table
  - name: Content
    items:
      - Enum Content
      - Text
      - H1-H6
      - Label
      - Number
      - Currency
      - Date
      - Time
      - DateTime
  - name: Lists
    items:
      - ControlList
      - ItemsControl
      - ListItem
      - UnorderedList
      - OrderedList
  - name: Hierarchy
    items:
      - HierarchicalControl
      - HierarchicalItem
      - HierarchicalListItem
      - HierarchicalUnorderedList
      - HierarchicalOrderedList
  - name: Frame

control-search:
  - name: General
    items:
      - Term
      - Multiple Terms
      - TermMatch
      - TermCase
      - Visibility
      - ScopeSource
  - name: Base Attributes
    items:
      - FindAttribute
      - TermFindAttribute
  - name: Find Attributes
    items:
      - FindById
      - FindByName
      - FindByClass
      - FindByXPath
      - FindByCss
      - FindByLabel
      - FindByFieldSet
      - FindByDescriptionTerm
      - FindByContent
      - FindByChildContent
      - FindByAttribute
      - FindByValue
      - FindByContentOrValue
      - FindByPlaceholder
      - FindByTitle
      - FindFirst
      - FindLast
      - FindByIndex
      - FindByColumnHeader
      - FindByColumnIndex
  - name: Settings Attributes
    items:
      - FindSettings
      - TermFindSettings
      - ControlFinding

triggers:
  - name: General
    items:
      - Trigger
      - TriggerEvents
      - TriggerPriority
      - TriggerScope
  - name: Verification
    items:
      - VerifyTitle
      - VerifyH1-H6
      - VerifyContent
      - VerifyContentMatches
      - VerifyExists
      - VerifyMissing
  - name: Waiting
    items:
      - Until
      - WaitFor
      - WaitForElement
      - Wait
      - WaitForJQueryAjax
      - WaitForAngularJSAjax
  - name: Performing
    items:
      - LogInfo
      - Screenshot
      - InvokeMethod
      - CloseAlertBox
      - CloseConfirmBox
      - PressKeys
      - PressEnter
      - PressEscape
      - PressTab
      - ScrollDown
      - ScrollUp
      - ClickParent
      - HoverParent

exclude:
  - LICENSE
  - README.md
  - atata-framework.github.io.sln
  - compilerconfig.json
  - compilerconfig.json.defaults
  - .gitignore

links:
    atata_github: https://github.com/atata-framework/atata
    atata_issues: https://github.com/atata-framework/atata/issues
    atata_webdriverextras_issues: https://github.com/atata-framework/atata-webdriverextras/issues
    atata_gitter: https://gitter.im/atata-framework/atata
    atata_twitter: https://twitter.com/AtataFramework
    atata_nuget: https://www.nuget.org/packages/Atata/
    atata_webdriverextras_nuget: https://www.nuget.org/packages/Atata.WebDriverExtras/
    atata_bootstrap_nuget: https://www.nuget.org/packages/Atata.Bootstrap/
    atata_kendoui_nuget: https://www.nuget.org/packages/Atata.KendoUI/
    atata_templates: https://marketplace.visualstudio.com/items?itemName=YevgeniyShunevych.AtataTemplates